FROM debian:11-slim

RUN apt update && \
    apt install -y apache2 php libapache2-mod-php php-mysql

RUN a2enmod rewrite
RUN service apache2 restart

WORKDIR /data

COPY ./entrypoint.sh ./entrypoint.sh

ENTRYPOINT ["/bin/sh", "/data/entrypoint.sh"]
