version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8080:80
    volumes:
      - ../src/:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  myadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: test_app
    volumes:
      - db:/var/lib/mysql/

volumes:
  db: {}
